from schemas.user import User
from schemas.balance import Balance
from schemas.platform import Platform
from schemas.trade_closed import Trade_closed
from schemas.trade_open import Trade_open
from schemas.transfert import Transfert
from schemas.wallet import Wallet
from schemas.wallet_evolution import Wallet_evolution
from schemas.synchronisation import Synchronisation
from schemas.mean_trade import Mean_trade
from schemas.transfert_ordered import Transfert_ordered