from routes.user import user
from routes.wallet import wallet
from routes.platform import platform
from routes.synchronisation import synchronisation
from routes.balance import balance
from routes.trade_closed import trade_closed
from routes.trade_open import trade_open
from routes.transfert import transfert
from routes.wallet_evolution import wallet_evolution
from routes.mean_trade import mean_trade
from routes.transfert_ordered import transfert_ordered